project:
  type: website

website:
  title: "Advanced illustration options"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Intro"
        contents:
          - href: landing.qmd
      - section: "pngs in plots"
        contents:
          - images_in_R_plots.qmd
      - section: "maps in quarto"
        contents:
          - quarto_maps.qmd  
        

format: 
  html:
    code-fold: true
    code-summary: "Click here to show the code"
    code-tools: true
    theme: 
      - spacelab
    self-contained: true
    page-layout: full
    toc: true
    toc-depth: 3
    css: styles.css
    include-in-header:
      - file: github-corner.html
# engine: knitr

execute:
  freeze: auto